"""add phone number

Revision ID: 201a5a3158ed
Revises: 47d6eb1a4e85
Create Date: 2022-10-08 19:51:58.948058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201a5a3158ed'
down_revision = '47d6eb1a4e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
